theme: jekyll-theme-merlot
title:               'Amartyo Roy'
description:         'Some Notes I made for the Software Engineering External Exams'
#about/contact
author:
  name:              Amartyo-Roy
  email:             amartyo09@gmail.com
  url:               https://amartyoroy.github.io/SEnotes
